spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/remember-please
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.sql: debug
  #org.hibernate.type: trace

ncp:
  maps:
    client.ID: e70f888j98
    client.secret: yBkovEXm77bAtJOYwukK8KcqzqXcz1ESTHBM9Pa0
    reverse-geocoding:
      url: https://naveropenapi.apigw.ntruss.com/map-reversegeocode/v2/gc
openapi:
  weather:
    endpoint: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    servicekey: ZxARRsGHdZL%2BVvVly2HeQxN6kBFsS3GdrphKBRy23pBpWFPBZiR92G73YrbXScToDFb8Qn3ZlFbvLuSIdqdlug%3D%3D
#ZxARRsGHdZL+VvVly2HeQxN6kBFsS3GdrphKBRy23pBpWFPBZiR92G73YrbXScToDFb8Qn3ZlFbvLuSIdqdlug==